name: Deploy
on:
  push:
    branches:
      - production
    paths:
      - 'src/**'
   workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Build step
        run: deno check --config=src/deno.json ${{ vars.ROOT }}/${{ vars.ENTRYPOINT }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ vars.PROJECT }}
          entrypoint: ${{ vars.ENTRYPOINT }}
          root: ${{ vars.ROOT }}
